---
# tasks file for mullvad-client
- name: preflight check
  include_tasks: preflight.yml

- name: include disto specific vars
  include_vars: '{{ lookup("first_found", file) }}'
  vars:
    file:
      - 'vars/{{ ansible_os_family | lower }}.yml'
      - 'vars/{{ ansible_distribution | lower }}.yml'

- name: generate dependencies
  set_fact:
    __role_dependencies: '{{ __dependencies + __distro_dependencies }}'

- name: include disto specific tasks
  include_tasks: '{{ lookup("first_found", file) }}'
  vars:
    file:
      - 'tasks/{{ ansible_os_family | lower }}.yml'
      - 'tasks/{{ ansible_distribution | lower }}.yml'

- name: account setup
  include_tasks: mullvad/account.yml

- name: relay setup
  include_tasks: 'mullvad/{{ mullvad_connection.relay.type }}.yml'

- name: configure relay
  ansible.builtin.command: 'mullvad relay set location {{ mullvad_connection.relay.country }} {{ mullvad_connection.relay.city }}{{ " " + mullvad_connection.relay.servername if mullvad_connection.relay.servername is defined else "" }}'

- name: autoconnect setup
  include_tasks: mullvad/autoconnect.yml
  when: mullvad_connection.connect_on_startup | default(false)

- name: connect
  include_tasks: mullvad/connect.yml
  when: mullvad_connection.connect_on_install | default(false)