---
- name: install role dependencies
  ansible.builtin.yum:
    name: '{{ __role_dependencies }}'
    state: present
    update_cache: true

- name: install package
  ansible.builtin.yum:
    name: '{{ mullvad_client_binary_url }}'
    state: present