---
- name: check connection status
  ansible.builtin.command: 'mullvad status'
  changed_when: false
  register: connection_status

- name: connect
  ansible.builtin.command: 'mullvad connect'
  when: '"Tunnel status: Disconnected" in connection_status.stdout'

- name: get connection status
  ansible.builtin.command: 'mullvad status'
  changed_when: false
  register: connection_status

- name: print connection status
  debug:
    msg: '{{ connection_status.stdout }}'